# Create me a postgresql db
version: '3.8'

services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "postgresql_data:/var/lib/postgresql/data"

volumes:
  postgresql_data:
    driver: local